package it.unibo.composeui.resources

object Strings {
    const val TOTAL_VALUE = "Total Value"
    const val NO_WALLETS = "No wallets available."
    const val WALLETS = "Wallets"
    const val ADD_WALLET = "Add Wallet"
    const val EDIT_AMOUNT = "Edit Amount"
    const val DELETE_WALLET = "Delete Wallet"
    const val CONFIRM_DELETE_WALLET = "Are you sure you want to delete this wallet?"
    const val CONFIRM = "Confirm"
    const val CANCEL = "Cancel"
    const val SAVE = "Save"
    const val CURRENCY = "Currency"
    const val AMOUNT = "Amount"
    const val DELTA = "Delta (+/-)"
    const val ADD_WALLET_DESCRIPTION = "Add Wallet"
    const val EDIT_DESCRIPTION = "Edit"
    const val DELETE_DESCRIPTION = "Delete"
    const val BASE_CURRENCY = "Base Currency"
    const val TARGET_CURRENCY = "Target Currency"
    const val SWAP_CURRENCIES = "Swap currencies"
    const val CONVERT = "Convert"
    const val CURRENCY_CONVERSION_RESULT = "%s %s = %.4f %s"
    const val ORDERED_BY_STRENGTH = "Currencies ordered by strength (based on 1 EUR)"
    const val HOME_LABEL = "Home"
    const val WALLET_LABEL = "Wallet"
    const val NO_CONNECTION = "No internet connection"
    const val HOME_DESCRIPTION = "Home"
    const val WALLET_DESCRIPTION = "Wallet"
    const val SPLASH_TITLE = "MoneyRate"
}
